/* ════════════════════════════════════════════════════
   BuiltByInstincts — Projects dataset
   Real copy from the live site, extended with:
   benefit / market / arch / repoUrl / uiUrl.

   ⚠ DUMMY DATA you should replace later is marked
     with /* DUMMY *​/ — market figures, live UI URLs,
     and a couple of private-repo links.
   ════════════════════════════════════════════════════ */

const ICONS = {
  github: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 .5C5.37.5 0 5.87 0 12.5c0 5.3 3.44 9.8 8.21 11.39.6.11.82-.26.82-.58v-2.03c-3.34.73-4.04-1.61-4.04-1.61-.55-1.39-1.34-1.76-1.34-1.76-1.09-.75.08-.73.08-.73 1.2.09 1.84 1.24 1.84 1.24 1.07 1.84 2.81 1.31 3.5 1 .11-.78.42-1.31.76-1.61-2.67-.3-5.47-1.34-5.47-5.95 0-1.31.47-2.39 1.24-3.23-.13-.3-.54-1.52.12-3.18 0 0 1.01-.32 3.3 1.23a11.5 11.5 0 0 1 6 0c2.29-1.55 3.3-1.23 3.3-1.23.66 1.66.25 2.88.12 3.18.77.84 1.23 1.92 1.23 3.23 0 4.62-2.81 5.64-5.49 5.94.43.37.82 1.1.82 2.22v3.29c0 .32.22.7.83.58A12.01 12.01 0 0 0 24 12.5C24 5.87 18.63.5 12 .5z"/></svg>',
  ui: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><path d="M15 3h6v6"/><path d="M10 14 21 3"/></svg>',
};

const PROJECTS = [
  {
    num: '01', name: 'MyPAIT', acc: '#00f5ff',
    logo: 'assets/mypait-logo.svg',
    shots: [
      'assets/mypait/shot-03.jpg',
      'assets/mypait/shot-04.jpg',
      'assets/mypait/shot-05.jpg',
      'assets/mypait/shot-07.jpg',
      'assets/mypait/shot-08.jpg',
    ],
    domain: 'iOS & Android · AI · Fitness',
    status: 'live', statusLabel: 'LIVE', statusColor: '#00ff88',
    filters: ['live', 'ai'],
    liner: 'Your gym in your pocket — an AI coach built around you, on iOS & Android.',
    impact: { stat: '70%', line: "of people quit generic fitness plans — MyPAIT's AI adapts to keep them." },
    headline: 'A gym that was finally built for you',
    lead: 'Generic plans ignore your equipment, schedule, injuries and goals — so people quit. <strong>MyPAIT</strong> is an intelligent fitness companion that uses AI to generate workout plans tailored to your exact profile. You chat, it builds, then it coaches you through every rep — shipped on both platforms via React + Capacitor and a fully native Kotlin/Compose Android port on the same Supabase backend.',
    benefit: 'Turns one-size-fits-none fitness apps into a personal coach that adapts to each user — the lever that lifts retention, daily active use and word-of-mouth growth.',
    market: [
      { big: '$12B', cap: 'AI fitness app market by 2030 /* DUMMY */' },
      { big: '70%', cap: 'of users quit generic plans in 90 days /* DUMMY */' },
      { big: '2', cap: 'native platforms at full parity' },
    ],
    arch: ['Chat onboarding', 'Gemini AI engine', 'Workout generator', 'Supabase store', 'iOS · Android client'],
    highlights: [
      'Conversational onboarding that maps your full fitness profile',
      'Dynamic workout splits generated by Gemini AI',
      'Live session guidance with form cues & exercise swaps',
      'Progress tracking — streaks, volume & personal bests',
      'Native Kotlin/Compose Android port at full feature parity',
    ],
    stack: ['React / Vite', 'Capacitor', 'Kotlin', 'Jetpack Compose', 'Supabase', 'Gemini AI'],
    repoUrl: 'https://github.com/Chanman22git/my-pait',
    uiUrl: 'https://mypait.app', uiDummy: true, /* DUMMY */
  },
  {
    num: '03', name: 'Penny Drop', acc: '#00e5b0',
    domain: 'Web · Fintech · AI',
    status: 'dev', statusLabel: 'IN DEVELOPMENT', statusColor: '#ffaa00',
    filters: ['dev', 'ai'],
    liner: 'Every subscription you pay for should be intentional — pulled straight from your inbox.',
    impact: { stat: '₹13.2K', line: "leaked per user each year on forgotten subscriptions — found and cut." },
    headline: "You're paying for things you've forgotten exist",
    lead: 'Subscriptions slip through on different cards, auto-renew without a whisper, and pile up unnoticed. <strong>Penny Drop</strong> is a subscription-intelligence layer that pulls invoices straight from your Gmail, surfaces what you are actually paying for, and tells you what is worth keeping — built for the generation that subscribes to everything and audits nothing.',
    benefit: 'Recovers real money users are quietly leaking — an average of ₹13,200 a year — by making every recurring charge visible, contextual and cancellable.',
    market: [
      { big: '₹13.2K', cap: 'avg. annual savings per user' },
      { big: '₹2.4L Cr', cap: 'India digital subscriptions market /* DUMMY */' },
      { big: '0', cap: 'manual entry — fully auto-extracted' },
    ],
    arch: ['Gmail ingest', 'Invoice parser', 'AI research', 'Supabase', 'Renewal dashboard'],
    highlights: [
      'Auto-extracts subscriptions from Gmail — zero manual entry',
      'Contextual AI research on every app & service you pay for',
      'Upcoming renewal tracker with 7-day cost projections',
      'Smart categories: Productivity, Streaming, Finance & more',
      'Actionable savings surfaced per subscription',
    ],
    stack: ['Next.js', 'Gmail API', 'AI Research', 'Supabase'],
    repoUrl: 'https://github.com/Chanman22git/Penny-Drop',
    uiUrl: 'https://pennydrop.app', uiDummy: true, /* DUMMY */
  },
  {
    num: '04', name: 'Cost Protocol', acc: '#ff6b2b',
    domain: 'AI Governance · Agents · OSS',
    status: 'poc', statusLabel: 'PROOF OF CONCEPT', statusColor: '#ff6b2b',
    filters: ['poc', 'ai', 'oss'],
    liner: 'AI agents spend your money. Now you can see exactly where — and prove it.',
    impact: { stat: '$50B+', line: "in agentic AI spend by 2028 — made auditable down to each tool call." },
    headline: 'AI agents are spending money — and nobody can explain how',
    lead: 'When an AI agent books travel it reasons, calls tools and negotiates across providers — generating cost at every step, not just at checkout. <strong>Cost Protocol</strong> is a proof-of-concept for AIGP, an open standard for tracking, attributing and auditing the true cost of AI agent activity. Every token, tool call and agent-to-agent handoff is cryptographically chained into an audit trail.',
    benefit: 'Gives finance, risk and engineering teams a verifiable, tamper-evident audit trail for autonomous AI spend — turning agentic cost from a black box into an accountable line item.',
    market: [
      { big: '$50B+', cap: 'projected agentic AI spend by 2028 /* DUMMY */' },
      { big: '100%', cap: 'of inferences & tool calls attributed' },
      { big: 'ES256', cap: 'JWS-signed, Merkle-hashed audit chain' },
    ],
    arch: ['Agent swarm (LangGraph)', 'Cost instrumentation', 'JWS ES256 signing', 'Merkle SHA-256 chain', 'Streamlit audit UI'],
    highlights: [
      'AIGP open standard instruments every inference, tool call & handoff',
      'Multi-agent travel scenario — flight, hotel & transport agents in parallel',
      'Every AI cost attributed to the exact agent, step & provider',
      'Cryptographic audit trail — JWS ES256 signing + Merkle-SHA256 hashing',
      'Fully local — zero external dependencies beyond a single API key',
    ],
    stack: ['Python', 'LangGraph', 'Claude API', 'Streamlit', 'SQLite', 'JWS ES256'],
    repoUrl: 'https://github.com/Chanman22git/Project-Cost-Protocol',
    uiUrl: '#', uiDummy: true, /* DUMMY — no public UI yet */
  },
  {
    num: '05', name: 'Project Utopia', acc: '#aa44ff',
    domain: 'Data · AI Agent · Platform',
    status: 'dev', statusLabel: 'IN DEVELOPMENT', statusColor: '#aa44ff',
    filters: ['dev', 'ai'],
    liner: 'From raw data to production-ready — in minutes, not weeks.',
    impact: { stat: 'Minutes', line: "What took weeks of data engineering now takes minutes, not tickets." },
    headline: 'Onboarding a dataset takes weeks. It shouldn\u2019t.',
    lead: 'Every new data source kicks off the same painful loop — manual schema mapping, hand-written pipelines, governance tickets stuck in queues. <strong>Project Utopia</strong> is an AI-powered data-onboarding agent that automates the full lifecycle from raw ingestion to consumption-ready views. LangGraph orchestrates an 8-step agentic workflow with human-in-the-loop checkpoints, every approval committed to Git.',
    benefit: 'Collapses weeks of data-engineering effort into minutes, freeing scarce engineering capacity and getting trustworthy data into production dramatically faster.',
    market: [
      { big: '$25B', cap: 'DataOps & integration tooling market /* DUMMY */' },
      { big: '8', cap: 'agentic steps, human-in-the-loop' },
      { big: 'Git', cap: 'as the single source of truth' },
    ],
    arch: ['Multi-source ingest', 'LangGraph 8-step agent', 'Soda + ODCS contracts', 'Iceberg + DuckDB', 'DataHub catalog'],
    highlights: [
      'LangGraph agentic workflow — 8 steps with human-in-the-loop gates',
      'Multi-source ingestion — files, Postgres, Kaggle, FRED, Hugging Face',
      'Schema-aware Q&A captures joins, dedup keys & PII masking before codegen',
      'Data quality enforced via Soda Core (SodaCL) & Data Contract CLI (ODCS)',
      'Full governance — DataHub catalog, lineage, access policies & observability',
    ],
    stack: ['LangGraph', 'DuckDB', 'Apache Airflow', 'Apache Iceberg', 'DataHub OSS', 'Soda Core', 'MinIO'],
    repoUrl: 'https://github.com/Chanman22git/Project-Utopia',
    uiUrl: '#', uiDummy: true, /* DUMMY */
  },
  {
    num: '02', name: 'EvalLib', acc: '#f5c542',
    domain: 'AI Governance · Observability · OSS',
    status: 'poc', statusLabel: 'PROOF OF CONCEPT', statusColor: '#f5c542',
    filters: ['poc', 'ai', 'oss'],
    liner: 'Governance for AI agents — every eval, version & verdict, traceable.',
    impact: { stat: '$16B', line: "AI-governance market — EvalLib proves agents behave, with receipts." },
    headline: 'AI agents run in production — and no one can prove they behave',
    lead: 'Gateways, tracers and eval frameworks all see part of the picture but live in silos. <strong>EvalLib</strong> is the governance and experience layer above tools like Phoenix and Datadog, anchored on the enterprise model gateway. Every call flows gateway → trace → eval → OpenTelemetry event → a UI with full governance context: which eval ran, what version, who approved it, the verdict, and a link back to the trace.',
    benefit: 'Lets enterprises prove their AI agents are governed — turning compliance from a bolted-on spreadsheet into a live, queryable system of record.',
    market: [
      { big: '$16B', cap: 'AI governance market by 2030 /* DUMMY */' },
      { big: 'OTel', cap: 'GenAI spans with PII redaction' },
      { big: '1', cap: 'control plane above Phoenix/Datadog' },
    ],
    arch: ['Model gateway', 'Trace capture', 'Eval runner', 'OTel GenAI event', 'Governance UI'],
    highlights: [
      'A control plane above Phoenix/Datadog — not another tracer',
      'Live calls flow gateway → trace → eval → OTel event → UI',
      'Every verdict carries governance context: version, approver & trace link',
      'OpenTelemetry GenAI spans with PII redaction at the collector',
      'Local-first — single-node POC, docker compose up',
    ],
    stack: ['Phoenix', 'OpenTelemetry', 'FastAPI', 'React', 'Python', 'Docker'],
    repoUrl: 'https://github.com/Chanman22git/EvalLib',
    uiUrl: '#', uiDummy: true, /* DUMMY */
  },
  {
    num: '06', name: 'Project Dupin', acc: '#ff5c8a',
    domain: 'AI Agents · Product Research',
    status: 'poc', statusLabel: 'PROOF OF CONCEPT', statusColor: '#ff5c8a',
    filters: ['poc', 'ai'],
    liner: 'AI agents that run product-discovery interviews — at scale.',
    impact: { stat: '20×', line: "more discovery interviews per PM — AI agents run them at scale." },
    headline: 'Product discovery doesn\u2019t scale — so most teams skip it',
    lead: 'A PM can run maybe five discovery interviews a week, then drowns in transcripts. <strong>Project Dupin</strong> is an AI-powered user-research platform: define a product context and objective, then deploy conversational AI agents to interview users at scale. Dupin synthesizes findings across every conversation — even flagging gaps between what the product claims and what users actually experience.',
    benefit: 'Scales product discovery from five interviews a week to hundreds — so roadmaps are built on evidence across many users instead of the loudest opinion in the room.',
    market: [
      { big: '$1.2B', cap: 'user-research software market /* DUMMY */' },
      { big: '20×', cap: 'more interviews per PM per week /* DUMMY */' },
      { big: '3', cap: 'context formats: PDF, DOCX, PPTX' },
    ],
    arch: ['Context (PRD/DOCX)', 'AI interview agents', 'Transcript synthesis', 'Insight + gap engine', 'SQLite store'],
    highlights: [
      'Conversational AI agents run structured discovery interviews at scale',
      'Scoped sessions per feature, scenario, persona or use case',
      'Synthesizes insights across every conversation automatically',
      'Flags discrepancies between product claims & user reality',
      'Ingests PRDs, docs & specs as context — PDF, DOCX & PPTX',
    ],
    stack: ['Python', 'Streamlit', 'Claude API', 'SQLite'],
    repoUrl: 'https://github.com/Chanman22git/Project-Dupin',
    uiUrl: '#', uiDummy: true, /* DUMMY */
  },
  {
    num: '07', name: 'Pattang', acc: '#4ea8ff',
    domain: 'Legal Tech · SaaS · India',
    status: 'dev', statusLabel: 'IN DEVELOPMENT', statusColor: '#4ea8ff',
    filters: ['dev'],
    liner: "The solo advocate's briefcase — cases, documents & deadlines in one place.",
    impact: { stat: '1.4M+', line: "solo advocates in India — one workspace replaces Word, memory & tabs." },
    headline: 'Solo advocates run a practice on memory and Microsoft Word',
    lead: 'A solo advocate in India juggles dozens of matters — each with its own parties, facts, deadlines and near-identical documents rebuilt by copy-pasting old files. <strong>Pattang</strong> is a workspace built for them: it generates recurring legal documents from reusable templates, keeps every document, fact, party and deadline per matter together, and lets advocates author in Google Docs inside their own Drive — with statute and case-law search from Indian Kanoon.',
    benefit: "Gives India's 1.4M+ solo advocates a single workspace, replacing Word + memory + a dozen browser tabs — multi-user-ready with row-level security from day one.",
    market: [
      { big: '1.4M+', cap: 'advocates in India /* DUMMY */' },
      { big: '0', cap: 'documents rebuilt from scratch' },
      { big: 'RLS', cap: 'row-level security on every table' },
    ],
    arch: ['Case workspace', 'Template engine', 'Google Docs / Drive', 'Indian Kanoon search', 'Hearing calendar'],
    highlights: [
      'Generate petitions, appeals & notices from learnable templates',
      'Every document, party, fact & deadline kept together per case',
      "Author & edit as Google Docs in the advocate's own Drive",
      'On-demand statute & case-law search via Indian Kanoon',
      "Hearing & deadline calendar from the advocate's cause-list",
    ],
    stack: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Google Docs API'],
    repoUrl: 'https://github.com/Chanman22git/Pattang',
    uiUrl: '#', uiDummy: true, /* DUMMY */
  },
];

const FILTER_DEFS = [
  { key: 'all', label: 'All' },
  { key: 'live', label: 'Live' },
  { key: 'dev', label: 'In Dev' },
  { key: 'poc', label: 'POC' },
  { key: 'ai', label: 'AI' },
  { key: 'oss', label: 'Open Source' },
];

/* Display order follows the num field (MyPAIT 01, EvalLib 02, …). */
PROJECTS.sort((a, b) => a.num.localeCompare(b.num));

/* ════════════════════════════════════════════════════
   TECH_ICONS — one inline SVG per tool, keyed by the
   exact stack label. Reused from the live site's chips,
   plus a few new marks. Fallback for anything unmatched.
   ════════════════════════════════════════════════════ */
const TECH_ICONS = {
  'React': '<svg viewBox="0 0 24 24" fill="#61dafb"><circle cx="12" cy="12" r="2"/><path fill="none" stroke="#61dafb" stroke-width="1" d="M12 5.5c5 0 9 2.9 9 6.5s-4 6.5-9 6.5-9-2.9-9-6.5 4-6.5 9-6.5z"/><path fill="none" stroke="#61dafb" stroke-width="1" d="M8.5 6.8c2.5-4.3 6-6.9 7.8-5.9s1.4 5.4-1.1 9.7-6 6.9-7.8 5.9-1.4-5.4 1.1-9.7z"/><path fill="none" stroke="#61dafb" stroke-width="1" d="M8.5 17.2c-2.5-4.3-2.9-8.7-1.1-9.7s5.3 1.6 7.8 5.9 2.9 8.7 1.1 9.7-5.3-1.6-7.8-5.9z"/></svg>',
  'React / Vite': '<svg viewBox="0 0 24 24" fill="#61dafb"><circle cx="12" cy="12" r="2"/><path fill="none" stroke="#61dafb" stroke-width="1" d="M12 5.5c5 0 9 2.9 9 6.5s-4 6.5-9 6.5-9-2.9-9-6.5 4-6.5 9-6.5z"/><path fill="none" stroke="#61dafb" stroke-width="1" d="M8.5 6.8c2.5-4.3 6-6.9 7.8-5.9s1.4 5.4-1.1 9.7-6 6.9-7.8 5.9-1.4-5.4 1.1-9.7z"/><path fill="none" stroke="#61dafb" stroke-width="1" d="M8.5 17.2c-2.5-4.3-2.9-8.7-1.1-9.7s5.3 1.6 7.8 5.9 2.9 8.7 1.1 9.7-5.3-1.6-7.8-5.9z"/></svg>',
  'Capacitor': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#0a1428"/><path d="M4.5 4.5h8L4.5 12.5z" fill="#53b9ff"/><path d="M19.5 19.5h-8l8-8z" fill="#119eff"/></svg>',
  'Kotlin': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#1b0a2e"/><path d="M5 5h14L12 12l7 7H5z" fill="#a97bff"/></svg>',
  'Jetpack Compose': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#0a1f33"/><rect x="6" y="6" width="6" height="6" fill="#4285f4"/><rect x="12" y="9" width="6" height="6" fill="#5e97f6" opacity="0.7"/></svg>',
  'Supabase': '<svg viewBox="0 0 24 24" fill="#3ecf8e"><path d="M11.9 1.036c-.015-.986-1.26-1.41-1.874-.637L.764 12.05C.111 12.876.706 14.09 1.824 14.09h9.174l.902 8.874c.015.987 1.26 1.41 1.874.637l9.261-11.652c.652-.826.057-2.038-1.06-2.038h-9.175z"/></svg>',
  'Gemini AI': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#0a1628"/><path d="M12 3c0 5 3 8 9 9-6 1-9 4-9 9 0-5-3-8-9-9 6-1 9-4 9-9z" fill="#8ab4f8"/></svg>',
  'Next.js': '<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="11" fill="#000"/><path d="M9 8v8M15.5 8v5.5L9.5 8" stroke="#fff" stroke-width="1.4" stroke-linecap="round"/></svg>',
  'Gmail API': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#0a0a0a"/><path d="M4 7v10h2.5V11l5.5 4 5.5-4v6H20V7l-8 5.5z" fill="#ea4335"/></svg>',
  'AI Research': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#150a28"/><circle cx="11" cy="10" r="4" stroke="#aa44ff" stroke-width="1.5"/><path d="M14 13.5l4 4" stroke="#aa44ff" stroke-width="1.8" stroke-linecap="round"/><path d="M11 6V4M7 7.5L5.5 6M15 7.5L16.5 6" stroke="#aa44ff" stroke-width="1.5" stroke-linecap="round"/></svg>',
  'Python': '<svg viewBox="0 0 24 24"><path fill="#3776ab" d="M12 1.5c-2.4 0-2.3 1-2.3 1l.01 1.1H12v.6H6.8s-1.6-.2-1.6 2.3c0 2.5 1.4 2.4 1.4 2.4h1.5V9.2s-.1-1.4 1.4-1.4h2.7s1.3 0 1.3-1.3V2.8s.2-1.3-2.5-1.3zm-1.3 1c.3 0 .5.2.5.5s-.2.5-.5.5-.5-.2-.5-.5.2-.5.5-.5z"/><path fill="#ffd43b" d="M12 22.5c2.4 0 2.3-1 2.3-1l-.01-1.1H12v-.6h5.2s1.6.2 1.6-2.3c0-2.5-1.4-2.4-1.4-2.4h-1.5v1.3s.1 1.4-1.4 1.4h-2.7s-1.3 0-1.3 1.3v2.7s-.2 1.3 2.5 1.3zm1.3-1c-.3 0-.5-.2-.5-.5s.2-.5.5-.5.5.2.5.5-.2.5-.5.5z"/></svg>',
  'LangGraph': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#1c3a5e"/><circle cx="7" cy="12" r="2.5" fill="#1c8ef9"/><circle cx="17" cy="7" r="2.5" fill="#1c8ef9"/><circle cx="17" cy="17" r="2.5" fill="#1c8ef9"/><path d="M9 11l6-3M9 13l6 3" stroke="#1c8ef9" stroke-width="1.5" stroke-linecap="round"/></svg>',
  'Claude API': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#1a0f0a"/><path d="M7 17l3.5-10 3.5 10M8.5 13h5" stroke="#d4a27f" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><circle cx="18" cy="8" r="2" fill="#d4a27f"/></svg>',
  'Streamlit': '<svg viewBox="0 0 24 24" fill="#ff4b4b"><path d="M14.898 2.572a.5.5 0 0 0-.796 0L7.36 11.4a.5.5 0 0 0 .398.8h13.485a.5.5 0 0 0 .397-.8l-6.742-8.828zM14.898 14.372a.5.5 0 0 0-.796 0l-6.742 8.828a.5.5 0 0 0 .398.8h13.485a.5.5 0 0 0 .397-.8l-6.742-8.828z"/></svg>',
  'SQLite': '<svg viewBox="0 0 24 24" fill="#44a8dd"><path d="M21.678.521C20.467-.29 19.087.098 18.044.917c-1.533 1.19-2.74 3.354-3.443 5.596-.47-1.56-1.43-2.825-2.823-2.9C7.425 3.306 1.066 7.3.104 12.847c-.62 3.573.448 7.03 2.733 9.184 1.033.967 2.283 1.633 3.637 2.013C4.33 23.925 2.99 22.39 2.66 20.021c-1.574-2.123-2.21-5.064-1.665-7.84C2.123 6.484 7.3 2.757 11.849 3.678c1.225.245 2.34.77 3.285 1.502-.128.655-.22 1.314-.264 1.977-.105 1.584.056 3.16.456 4.67.44 1.635 1.15 3.048 2.082 4.048-1.26 4.05-.43 7.38 2.52 8.22.278.08.56.132.843.163C23.715 23.914 24 21.645 24 19.157V4.843C24 2.355 22.888.521 21.678.521z"/></svg>',
  'JWS ES256': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#1a1000"/><rect x="5" y="11" width="14" height="9" rx="2" stroke="#f5a623" stroke-width="1.5"/><path d="M8 11V7a4 4 0 0 1 8 0v4" stroke="#f5a623" stroke-width="1.5" stroke-linecap="round"/><circle cx="12" cy="15.5" r="1.5" fill="#f5a623"/></svg>',
  'DuckDB': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="12" fill="#1a1400"/><circle cx="12" cy="12" r="8" fill="#ffcc00" opacity="0.15" stroke="#ffcc00" stroke-width="1.5"/><circle cx="9.5" cy="12" r="3" fill="#ffcc00"/><circle cx="14.5" cy="12" r="3" fill="#1a1400" stroke="#ffcc00" stroke-width="1.5"/></svg>',
  'Apache Airflow': '<svg viewBox="0 0 24 24" fill="#017cee"><path d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2zm0 18c-4.418 0-8-3.582-8-8s3.582-8 8-8 8 3.582 8 8-3.582 8-8 8zm-1-13v6l5 3-1 1.73-6-3.73V7h2z"/></svg>',
  'Apache Iceberg': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#071a2b"/><polygon points="12,3 21,18 3,18" fill="none" stroke="#5ea7d4" stroke-width="1.5"/><polygon points="12,9 17,18 7,18" fill="#5ea7d4" opacity="0.4"/></svg>',
  'DataHub OSS': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#041c1a"/><circle cx="12" cy="7" r="2.5" fill="#09b7a5"/><circle cx="5" cy="17" r="2.5" fill="#09b7a5"/><circle cx="19" cy="17" r="2.5" fill="#09b7a5"/><path d="M12 9.5v3M12 12.5l-5 3M12 12.5l5 3" stroke="#09b7a5" stroke-width="1.5" stroke-linecap="round"/></svg>',
  'Soda Core': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#1a0a06"/><path d="M12 4c-4.4 0-8 2.7-8 6 0 2 1.3 3.7 3.3 4.8L6 20h12l-1.3-5.2C18.7 13.7 20 12 20 10c0-3.3-3.6-6-8-6z" fill="#ff6d4a" opacity="0.3" stroke="#ff6d4a" stroke-width="1.5"/></svg>',
  'MinIO': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#1a0509"/><path d="M7.286 2v20l4.357-3.64V6L7.286 2zm9.428 0l-4.357 3.63v12.74L16.714 22V2z" fill="#c72e49"/></svg>',
  'Phoenix': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#2a0a0a"/><path d="M12 3c1 3 4 4 4 8a4 4 0 0 1-8 0c0-1.5.5-2.5 1.2-3.2C9 11 9.5 13 11 13.5 10 11 12 7 12 3z" fill="#ff6b3d"/></svg>',
  'OpenTelemetry': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#13123a"/><circle cx="11" cy="13" r="3" fill="#f5a800"/><circle cx="17" cy="7" r="2" fill="#7b8cff"/><path d="M13.2 11l2.4-1.6" stroke="#7b8cff" stroke-width="1.4" stroke-linecap="round"/></svg>',
  'FastAPI': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="5" fill="#05312c"/><circle cx="12" cy="12" r="8" stroke="#009688" stroke-width="1.5"/><path d="M12 6l-3 7h3l-1 5 4-7h-3l1-5z" fill="#05ffd0"/></svg>',
  'Docker': '<svg viewBox="0 0 24 24" fill="#2496ed"><rect x="3" y="10" width="2.4" height="2.2"/><rect x="6" y="10" width="2.4" height="2.2"/><rect x="9" y="10" width="2.4" height="2.2"/><rect x="12" y="10" width="2.4" height="2.2"/><rect x="6" y="7.4" width="2.4" height="2.2"/><rect x="9" y="7.4" width="2.4" height="2.2"/><path d="M22 11.2c-.5-.3-1.5-.4-2.3-.2-.1-.8-.6-1.5-1.3-2l-.4-.3-.3.4c-.4.6-.6 1.5-.3 2.2H1.5c-.2 1.7.3 3.9 1.8 5.3 1.4 1.3 3.4 1.9 5.9 1.9 5.4 0 9.4-2.5 11.3-7 .7 0 2.2 0 2.9-1.6l.2-.3-.7-.4z"/></svg>',
  'TypeScript': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#3178c6"/><text x="12" y="16.5" text-anchor="middle" font-family="monospace" font-weight="700" font-size="9" fill="#fff">TS</text></svg>',
  'Tailwind CSS': '<svg viewBox="0 0 24 24" fill="#38bdf8"><path d="M12 6c-2.67 0-4.33 1.33-5 4 1-1.33 2.17-1.83 3.5-1.5.76.19 1.31.74 1.91 1.35C13.4 10.8 14.57 12 17 12c2.67 0 4.33-1.33 5-4-1 1.33-2.17 1.83-3.5 1.5-.76-.19-1.3-.74-1.91-1.35C15.6 7.2 14.43 6 12 6zM7 12c-2.67 0-4.33 1.33-5 4 1-1.33 2.17-1.83 3.5-1.5.76.19 1.3.74 1.91 1.35C8.4 16.8 9.57 18 12 18c2.67 0 4.33-1.33 5-4-1 1.33-2.17 1.83-3.5 1.5-.76-.19-1.3-.74-1.91-1.35C10.6 13.2 9.43 12 7 12z"/></svg>',
  'Google Docs API': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#0a2818"/><rect x="6" y="4" width="12" height="16" rx="1.5" fill="#4285f4"/><path d="M9 9h6M9 12h6M9 15h4" stroke="#fff" stroke-width="1.2" stroke-linecap="round"/></svg>',
  '_fallback': '<svg viewBox="0 0 24 24" fill="none"><rect width="24" height="24" rx="4" fill="#0c1f30"/><path d="M8 9l-3 3 3 3M16 9l3 3-3 3M13 7l-2 10" stroke="#4a7a8a" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>',
};
